//----------------- AUTOGENERATED ----------------------

parameter INPUT_FILE  = "c:/Maestria/DDA-2025/ProyectoFinal/RTL/carrier_recovery/input_data.txt";
parameter OUTPUT_FILE = "c:/Maestria/DDA-2025/ProyectoFinal/RTL/carrier_recovery/expected_output.txt";

integer input_fd, output_fd, scan_in, scan_out;
integer test_passed;
reg [NB_OUT_CARRIER_RECOVERY-1:0] expected_out_o_corrected_q;
reg [NB_OUT_CARRIER_RECOVERY-1:0] expected_out_o_corrected_i;

initial begin
    test_passed = 1;
    i_clock = 0;
    i_rst_n = 0;
    #10 i_rst_n = 1;

    // Open files
    input_fd = $fopen(INPUT_FILE, "r");
    output_fd = $fopen(OUTPUT_FILE, "r");
    if (input_fd == 0 || output_fd == 0) begin
        $display("Error: Could not open input or output file.");
        $finish;
    end
// Read and apply inputs
    while (!$feof(input_fd) && !$feof(output_fd)) begin
        scan_in = $fscanf(input_fd, "%d %d\n", i_data_q,  i_data_i);
        scan_out = $fscanf(output_fd, "%d %d\n", expected_out_o_corrected_q,  expected_out_o_corrected_i);
        if (scan_in != 2 || scan_out != 1) begin
            $display("Error reading files");
            $finish;
        end
        
        @(posedge i_clock); // Wait for one clock cycle
        if (o_corrected_q !== expected_out_o_corrected_q) begin
            $display("Mismatch: expected=%d, got=%d at time: %t", expected_out_o_corrected_q, o_corrected_q, $time);
            test_passed = 0;
        end
        else begin
            $display("MATCH AT TIME %t", $time);
        end
        if (o_corrected_i !== expected_out_o_corrected_i) begin
            $display("Mismatch: expected=%d, got=%d at time: %t", expected_out_o_corrected_i, o_corrected_i, $time);
            test_passed = 0;
        end
        else begin
            $display("MATCH AT TIME %t", $time);
        end
    end

// Close files
    $fclose(input_fd);
    $fclose(output_fd);
    if(test_passed)
        $display("TEST PASSED");
    else
        $display("TEST  FAILED");
    $finish;
end

//----------------- ENDAUTOGENERATED ----------------------

