module carrier_recovery_tb ();
    parameter NB_IN_CARRIER_RECOVERY   = 8;
    parameter NBF_IN_CARRIER_RECOVERY  = 7;
    parameter NB_OUT_CARRIER_RECOVERY  = 8;
    parameter NBF_OUT_CARRIER_RECOVERY = 7;

    wire signed [NB_OUT_CARRIER_RECOVERY - 1 : 0] o_corrected_i       ;
    wire signed [NB_OUT_CARRIER_RECOVERY - 1 : 0] o_corrected_q       ;
    reg  signed [NB_IN_CARRIER_RECOVERY  - 1 : 0] i_data_i            ;
    reg  signed [NB_IN_CARRIER_RECOVERY  - 1 : 0] i_data_q            ;
    reg                                           i_clock             ;
    reg                                           i_rst_n         ;

    always #5 i_clock = ~i_clock;

//----------------- AUTOGENERATED ----------------------

    parameter INPUT_FILE  = "c:/Maestria/DDA-2025/ProyectoFinal/RTL/carrier_recovery/input_data.txt";
    parameter OUTPUT_FILE = "c:/Maestria/DDA-2025/ProyectoFinal/RTL/carrier_recovery/expected_output.txt";
    parameter OUTPUT_FILE_ATAN_R = "c:/Maestria/DDA-2025/ProyectoFinal/RTL/carrier_recovery/expected_output_atan_r.txt";
    parameter OUTPUT_FILE_ATAN_A = "c:/Maestria/DDA-2025/ProyectoFinal/RTL/carrier_recovery/expected_output_atan_a.txt";
    parameter OUTPUT_FILE_PHASE_ERR = "c:/Maestria/DDA-2025/ProyectoFinal/RTL/carrier_recovery/expected_output_phase_err.txt";
    
    integer input_fd, output_fd, scan_in, scan_out, output_fd_atan_r, output_fd_atan_a, output_fd_phase_err;
    integer test_passed;

    reg [NB_OUT_CARRIER_RECOVERY-1:0] expected_out_o_corrected_q;
    reg [NB_OUT_CARRIER_RECOVERY-1:0] expected_out_o_corrected_i;

    reg [18-1:0] expected_out_o_atan_r;
    reg [18-1:0] expected_out_o_atan_a;    

    reg [18-1:0] expected_out_o_phase_err;    

    initial begin
        test_passed = 1;
        i_clock = 0;
        i_rst_n = 0;
        i_data_i = 0;
        i_data_q = 0;
        
        @(posedge i_clock); // Wait for one clock cycle

        i_rst_n = 1;
    
        // Open files
        input_fd = $fopen(INPUT_FILE, "r");
        output_fd = $fopen(OUTPUT_FILE, "r");

        output_fd_atan_r = $fopen(OUTPUT_FILE_ATAN_R, "r");
        output_fd_atan_a = $fopen(OUTPUT_FILE_ATAN_A, "r");
        output_fd_phase_err = $fopen(OUTPUT_FILE_PHASE_ERR, "r");
        
        
        if (input_fd == 0) begin
            $display("Error: Could not open input or output file.");
            $finish;
        end
    // Read and apply inputs
        while (!$feof(input_fd)) begin
            scan_in = $fscanf(input_fd, "%d %d\n", i_data_q,  i_data_i);
            scan_out = $fscanf(output_fd, "%d %d\n", expected_out_o_corrected_q,  expected_out_o_corrected_i);
            
            $fscanf(output_fd_atan_r, "%d\n", expected_out_o_atan_r);
            $fscanf(output_fd_atan_a, "%d\n", expected_out_o_atan_a);
            $fscanf(output_fd_phase_err, "%d\n", expected_out_o_phase_err);
            
            if (scan_in != 2) begin
                $display("Error reading files");
                $finish;
            end
            
            @(posedge i_clock); // Wait for one clock cycle
        end
    
    // Close files
        $fclose(input_fd);
        $fclose(output_fd);
        if(test_passed)
            $display("TEST PASSED");
        else
            $display("TEST  FAILED");
        $finish;
    end
    
    //----------------- ENDAUTOGENERATED ----------------------
        
 carrier_recovery #(
    .NB_IN_CARRIER_RECOVERY(NB_IN_CARRIER_RECOVERY),
    .NBF_IN_CARRIER_RECOVERY(NBF_IN_CARRIER_RECOVERY),
    .NB_OUT_CARRIER_RECOVERY(NB_OUT_CARRIER_RECOVERY),
    .NBF_OUT_CARRIER_RECOVERY(NBF_OUT_CARRIER_RECOVERY)
 )u_carrier_recovery (
    .o_corrected_i(o_corrected_i),
    .o_corrected_q(o_corrected_q),
    .i_data_i(i_data_i),
    .i_data_q(i_data_q),
    .i_clock(i_clock),
    .i_rst_n(i_rst_n)
);
    

endmodule