# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Maestria/DDA-2025/enviroment_test/enviroment_test.srcs/sources_1/ip/ram_i/ram_i.xci
# IP: The module: 'ram_i' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Maestria/DDA-2025/enviroment_test/enviroment_test.gen/sources_1/ip/ram_i/ram_i_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ram_i'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Maestria/DDA-2025/enviroment_test/enviroment_test.srcs/sources_1/ip/ram_i/ram_i.xci
# IP: The module: 'ram_i' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Maestria/DDA-2025/enviroment_test/enviroment_test.gen/sources_1/ip/ram_i/ram_i_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ram_i'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
