module lut_atan_tb();
    parameter NB_DATA_IN    = 8 ;
    parameter NB_DATA_OUT   = 16;

    wire [NB_DATA_OUT - 1 : 0] o_atan  ;      
    reg  [NB_DATA_IN  - 1 : 0] i_data_i;      
    reg  [NB_DATA_IN  - 1 : 0] i_data_q;      
    reg                        i_clock   ;      
    reg                        i_rst_n ;  

    always #10 i_clock = ~i_clock;

//----------------- AUTOGENERATED ----------------------

    parameter INPUT_FILE  = "c:/Maestria/DDA-2025/ProyectoFinal/RTL/div_lut/input_data.txt";
    parameter OUTPUT_FILE = "c:/Maestria/DDA-2025/ProyectoFinal/RTL/div_lut/expected_output.txt";
    
    integer input_fd, output_fd, scan_in, scan_out;
    integer test_passed;
    reg [NB_DATA_OUT-1:0] expected_out_o_atan;
    
    initial begin
        test_passed = 1;
        i_clock = 0;
        i_rst_n = 0;
        #10 i_rst_n = 1;
    
        // Open files
        input_fd = $fopen(INPUT_FILE, "r");
        output_fd = $fopen(OUTPUT_FILE, "r");
        if (input_fd == 0 || output_fd == 0) begin
            $display("Error: Could not open input or output file.");
            $finish;
        end
    // Read and apply inputs
        while (!$feof(input_fd) && !$feof(output_fd)) begin
            scan_in = $fscanf(input_fd, "%d %d\n", i_data_i,  i_data_q);
            scan_out = $fscanf(output_fd, "%d\n", expected_out_o_atan);
            if (scan_in != 2 || scan_out != 1) begin
                $display("Error reading files");
                $finish;
            end
            
            @(posedge i_clock); // Wait for one clock cycle
            if (o_atan !== expected_out_o_atan) begin
                $display("Mismatch: expected=%d, got=%d at time: %t", expected_out_o_atan, o_atan, $time);
                test_passed = 0;
            end
            else begin
                $display("MATCH AT TIME %t", $time);
            end
        end
    
    // Close files
        $fclose(input_fd);
        $fclose(output_fd);
        if(test_passed)
            $display("TEST PASSED");
        else
            $display("TEST  FAILED");
        $finish;
    end
    
    //----------------- ENDAUTOGENERATED ----------------------
    
    

lut_atan #(
    .NB_DATA_IN (NB_DATA_IN ),
    .NB_DATA_OUT(NB_DATA_OUT)
) u_lut_atan (
    .o_atan     (o_atan     ),
    .i_data_i   (i_data_i   ),
    .i_data_q   (i_data_q   ),
    .i_clock    (i_clock    ),
    .i_rst_n    (i_rst_n    )
);

endmodule
