# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Maestria/DDA-2025/ProyectoFinal/RTL/top_test_module/top_test.xdc

# Block Designs: bd/vio/vio.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vio || ORIG_REF_NAME==vio} -quiet] -quiet

# IP: bd/vio/ip/vio_vio_0_0/vio_vio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vio_vio_0_0 || ORIG_REF_NAME==vio_vio_0_0} -quiet] -quiet

# XDC: c:/Maestria/enviroment_test/enviroment_test.gen/sources_1/bd/vio/vio_ooc.xdc
