# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Maestria/DDA-2025/ProyectoFinal/RTL/carrier_recovery/carrier_recovery.xdc

# IP: ip/ram_atan/ram_atan.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ram_atan || ORIG_REF_NAME==ram_atan} -quiet] -quiet
