module phase_detector_tb ();
    parameter NB_IN_PD    = 8       ; 
    parameter NBF_IN_PD   = 7       ; 
    parameter NB_OUT_PD   = 18      ; 
    parameter NBF_OUT_PD  = 14      ;  
    wire  signed  [NB_OUT_PD - 1 : 0]     o_phase_error  ;
    reg   signed  [NB_IN_PD  - 1 : 0]     i_in_phase     ;
    reg   signed  [NB_IN_PD  - 1 : 0]     i_quadrature   ;
    reg                                   i_clock        ;
    reg                                   i_rst_n        ;

real phase_error_real;
real phase_error_deg;

real phase_error_real_a;
real phase_error_deg_a;

real phase_error_real_r;
real phase_error_deg_r;

always #5 i_clock = ~i_clock;

    parameter NB_DATA_OUT = NB_OUT_PD;

//----------------- AUTOGENERATED ----------------------

    // parameter INPUT_FILE  = "c:/Maestria/DDA-2025/ProyectoFinal/RTL/phase_detector/input_data.txt";
    // parameter OUTPUT_FILE = "c:/Maestria/DDA-2025/ProyectoFinal/RTL/phase_detector/expected_output.txt";
    
    // integer input_fd, output_fd, scan_in, scan_out;
    // integer test_passed;
    // reg [NB_DATA_OUT-1:0] expected_out_o_phase_error;
    
    initial begin

        i_clock = 0;
        i_in_phase  = 0;
        i_quadrature    = 0;
        i_rst_n = 0;
        #10 i_rst_n = 1;
        
        @(posedge i_clock)
        i_in_phase      =8'd20;
        i_quadrature    =8'd40;
        
        @(posedge i_clock)
        i_in_phase      =8'd200;
        i_quadrature    =8'd60;    

        @(posedge i_clock)
        i_in_phase      =8'd200;
        i_quadrature    =8'd200;    

        @(posedge i_clock)
        i_in_phase      =8'd60;
        i_quadrature    =8'd200;    

    end
    //     // Open files
    //     input_fd = $fopen(INPUT_FILE, "r");
    //     output_fd = $fopen(OUTPUT_FILE, "r");
    //     if (input_fd == 0 || output_fd == 0) begin
    //         $display("Error: Could not open input or output file.");
    //         $finish;
    //     end
    // // Read and apply inputs
    //     while (!$feof(input_fd) && !$feof(output_fd)) begin
    //         scan_in = $fscanf(input_fd, "%d %d\n", i_quadrature,  i_in_phase);
    //         scan_out = $fscanf(output_fd, "%d\n", expected_out_o_phase_error);
    //         if (scan_in != 2) begin
    //             $display("Error reading files");
    //             $finish;
    //         end
            
    //         @(posedge i_clock); // Wait for one clock cycle

                     
    //     end
    
    // // Close files
    //     $fclose(input_fd);
    //     $fclose(output_fd);
    //     if(test_passed)
    //         $display("TEST PASSED");
    //     else
    //         $display("TEST  FAILED");
    //     $finish;
    // end
    
    //----------------- ENDAUTOGENERATED ----------------------
    
    
// always @(o_phase_error) begin
//     phase_error_real = $itor($signed(o_phase_error)) / (1 << (NBF_OUT_PD)); // Convert signed fixed-point to real
//     phase_error_deg  = phase_error_real * 180.0 / 3.141592653589793;
//     $display("Phase Error: %f degrees", phase_error_deg);
// end

// always @(u_phase_detector.u_lut_atan_a.o_atan) begin
//     phase_error_real_a = $itor($unsigned(u_phase_detector.u_lut_atan_a.o_atan)) / (1 << (NBF_OUT_PD)); // Convert signed fixed-point to real
//     phase_error_deg_a  = phase_error_real_a * 180.0 / 3.141592653589793;
//     $display("atan_a: %f degrees", phase_error_deg_a);
// end

// always @(u_phase_detector.u_lut_atan_r.o_atan) begin
//     phase_error_real_r = $itor($unsigned(u_phase_detector.u_lut_atan_r.o_atan)) / (1 << (NBF_OUT_PD)); // Convert signed fixed-point to real
//     phase_error_deg_r  = phase_error_real_r * 180.0 / 3.141592653589793;
//     $display("%f +j %f", ($itor($signed(i_in_phase)) / (1 << 7)), $itor($signed(i_quadrature)) / (1 << 7));
//     $display("atan_r: %f degrees", phase_error_deg_r);
//     phase_error_real_r = $itor($unsigned(u_phase_detector.phase_r_converted)) / (1 << (NBF_OUT_PD)); // Convert signed fixed-point to real
//     phase_error_deg_r  = phase_error_real_r * 180.0 / 3.141592653589793;
//     $display("deg_r: %f degrees", phase_error_deg_r);
// end

phase_detector #(
    .NB_IN_PD       (NB_IN_PD           ),
    .NBF_IN_PD      (NBF_IN_PD          ),
    .NB_OUT_PD      (NB_OUT_PD          ),
    .NBF_OUT_PD     (NBF_OUT_PD         )
) u_phase_detector (    
    .o_phase_error  (o_phase_error      ),
    .i_in_phase     (i_in_phase         ),
    .i_quadrature   (i_quadrature       ),
    .i_clock        (i_clock            ),
    .i_rst_n        (i_rst_n            )
);


endmodule