# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Maestria/carrier_recovery/carrier_recovery.srcs/sources_1/ip/ram_atan_1/ram_atan.xci
# IP: The module: 'ram_atan' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Maestria/carrier_recovery/carrier_recovery.gen/sources_1/ip/ram_atan_1/ram_atan_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ram_atan'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Maestria/carrier_recovery/carrier_recovery.srcs/sources_1/ip/ram_atan_1/ram_atan.xci
# IP: The module: 'ram_atan' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Maestria/carrier_recovery/carrier_recovery.gen/sources_1/ip/ram_atan_1/ram_atan_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ram_atan'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
